name: publish

on:
  push:
    branches:
      - develop
    paths:
      - 'plugins/**/package.json'
      - 'plugins/**/src/**'

env: 
  NODE_VERSION: 18.x

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changed_files::$changed_files"

      - name: Display changed files
        run: |
            echo "Changed files: ${{ steps.changes.outputs.changed_files }}"

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install yarn 2
        run: npm install -g yarn@berry

      - name: Set GitHub npm token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      - name: Install semver
        run: npm install -g semver

      - name: Check and publish plugins
        run: |
          for plugin in file1 file2 file3 file4; do
            PACKAGE_NAME="@kubernetes-administration/$plugin"
            NEW_VERSION=$(jq -r ".version" plugins/$plugin/package.json)
            EXISTING_VERSION=$(npm info $PACKAGE_NAME --registry=https://npm.pkg.github.com/Kubernetes-administration version 2>/dev/null)

            if [ -z "$EXISTING_VERSION" ] || semver -r ">$EXISTING_VERSION" "$NEW_VERSION"; then
              echo "Publishing $PACKAGE_NAME ($NEW_VERSION)..."
              npm publish plugins/$plugin/ --registry=https://npm.pkg.github.com/Kubernetes-administration --verbose
            else
              echo "Skipping $PACKAGE_NAME: Version $NEW_VERSION is not greater than existing version $EXISTING_VERSION"
            fi
          done